### ISSUE TITLE
P2P Market : Publish an Add quick instructions & Improvments

### ISSUE THREAD

**Issue by sLiinuX** [sLiinuX/wxRaven#124]

**Comment by sLiinuX** [comment]
![image](https://user-images.githubusercontent.com/90932021/154784179-a1ca74bd-e0f1-4ee9-b807-c2f93f3ddffe.png)
proposed by bless yer heart

**Comment by Chief-Prince-Of-Function** [comment]
Better heading

Tips to create swap:
 - Utilize minimize button on header
 - Only select the ownership token 'MYTOKEN!' if intended
 - P2P Channel Asset: should be set to "XXXXXXX"
